### ISSUE TITLE
the __morestack in ecall when using the multithreads

### ISSUE THREAD

**Issue by smartiov** [intel/linux-sgx#437]
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f4b80653902 in sig_handler(int, siginfo_t*, void*) () from /usr/lib/x86_64-linux-gnu/libsgx_urts.so
#2  <signal handler called>
#3  0x00007f4b8064c6f8 in __morestack () from /usr/lib/x86_64-linux-gnu/libsgx_urts.so
#4  0x00007f4b8064f61f in CEnclave::ecall(int, void const*, void*, bool) () from /usr/lib/x86_64-linux-gnu/libsgx_urts.so
#5  0x00007f4b8065113f in _sgx_ecall(unsigned long, int, void const*, void*, bool) [clone .part.0] () from /usr/lib/x86_64-linux-gnu/libsgx_urts.so

=====
1. i have confronted the ecall coredump in multithreads ecall, but when i changed the 6 threads to 2 threads, the program can continue but core again. 
2.it seems not the interface parameters problem or multithreads question.
about other caused?

**Comment by ZongminGu** [comment]
Are you using sgx-gdb? It seems that you are using normal gdb, as the result you are not able to see what happened inside enclave. Base on the current frame information, I guess it crashed inside enclave.

BTW: The sgx core dump file support is working in progress. So you need to user sgx-gdb attach the application before the crash happened.
