### ISSUE TITLE
error when running in SampleAttestationTLS

### ISSUE THREAD

**Issue by PeizhongQiu** [intel/linux-sgx#953]
I run the SampleAttestationTLS, but I met an error:
```shell
[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe065
 null certificate
please check the error 0xe065
null cert
TLS server:  unable to load certificate and private key on the server
``` 
I saw /opt/intel/sgx-dacp-pccs/logs: 
```shell
2023-05-29 08:26:48.863 [error]: Intel PCS server returns error(404).
2023-05-29 08:26:48.863 [error]: Intel PCS server returns error. Error code : 404
2023-05-29 08:26:48.863 [error]: Error: No cache data for this platform.
```

**Comment by llly** [comment]
You need to install `sgx-ra-service` or install and run `sgx-pck-id-retrieval-tool` 
 (README: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/tools/PCKRetrievalTool) to register platform to Intel PCS server.
Refer https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_DCAP_Multipackage_SW.pdf Section 3.1 and 3.2

**Comment by PeizhongQiu** [comment]
I installed sgx-ra-service and run sgx-pck-id-retrieval-tool, but got an error:
```shell
/opt/intel/sgx-pck-id-retrieval-tool$ sudo PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Error: unexpected error occurred while sending data to cache server.
Registration status has been set to completed status.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

**Comment by llly** [comment]
Did you edit the config file `/opt/intel/sgx-pck-id-retrieval-tool/network_setting.conf` accoding to PCCS?

**Comment by llly** [comment]
It seems to be PCCS HTTPS key issue. You can run `sudo /opt/intel/sgx-dcap-pccs/install.sh` and `sudo /opt/intel/sgx-dcap-pccs/startup.sh` to regenerate HTTPS key.  Then run `PCKIDRetrievalTool` and the sample.

**Comment by PeizhongQiu** [comment]
I tried but get the same error. The key is used as follows: 
![截屏2023-06-09 16 26 20](https://github.com/intel/linux-sgx/assets/27813926/aa658b7d-6afa-41d4-99de-724a3312b32e)

**Comment by llly** [comment]
Can you run `https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode/QuoteGenerationSample` and check the error message?  It's `Prerequisites` of `SampleAttestationTLS`. 
And `curl -v  --insecure https://localhost:8081/sgx/certification/v4/platforms`.  "Authentication failed." is expected output if PCCS is working properly.

**Comment by PeizhongQiu** [comment]
I run the QuoteGenerationSample, and error message is : 
```shell
~/sgx/linux-sgx/external/dcap_source/SampleCode/QuoteGenerationSample$ sudo ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe047
Error in sgx_qe_get_target_info. 0xe047
``` 
And 
```shell
sudo curl -v  --insecure https://localhost:8081/sgx/certification/v4/platforms
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  start date: Jun  6 09:15:51 2023 GMT
*  expire date: Jun  5 09:15:51 2024 GMT
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /sgx/certification/v4/platforms HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.81.0
> Accept: */*
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< X-Powered-By: Express
< Request-ID: b5a5893abc074b398051b88352d22e85
< Content-Type: text/html; charset=utf-8
< Content-Length: 22
< ETag: W/"16-+ULf/l3ur54bYnti3HLVXuLEgG8"
< Date: Fri, 09 Jun 2023 09:03:23 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
Authentication failed.
```

**Comment by llly** [comment]
Now  run `PCKIDRetrievalTool`, does it works?

**Comment by PeizhongQiu** [comment]
Nothing changed.

**Comment by llly** [comment]
Let's double check the config
```
    "UserTokenHash" : "",
    "AdminTokenHash" : "",
```
There are sha265 values in these two items, you delete them when copy and paste here, right?
 
And, you can try to change   `"CachingFillMode" : "REQ"` to `"CachingFillMode" : "LAZY"` and restart PCCS.

**Comment by PeizhongQiu** [comment]
Yes. There are sha265 values in these two items. I change the CachingFillMode,but nothing changed.

**Comment by llly** [comment]
I don't see any issue in config files. `PCKIDRetrievalTool` should work now.

**Comment by PeizhongQiu** [comment]
But the output is:
```shell
Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Error: unexpected error occurred while sending data to cache server.
Registration status has been set to completed status.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```

**Comment by PeizhongQiu** [comment]
And the output of QuoteGenerationSample is:
```shell
~/sgx/linux-sgx/external/dcap_source/SampleCode/QuoteGenerationSample$ ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

[error_driver2api sgx_enclave_common.cpp:266] Enclave not authorized to run, .e.g. provisioning enclave hosted in app without access rights to /dev/sgx_provision. You need add the user id to group sgx_prv or run the app as root.
[load_pce ../pce_wrapper.cpp:195] Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:4004.
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe00d
```

**Comment by jsun39** [comment]
when you tried to run PCKIDRetrieval tool, what is PCCS's new output log?

**Comment by PeizhongQiu** [comment]
When I run QuoteGenerationSample, the /opt/intel/sgx-dacp-pccs/logs/pccs_server.log adds:
```shell
2023-06-10 01:36:20.877 [info]: Client Request-ID : 9e06a0f59e254382b40a6d75faa39d81
2023-06-10 01:36:21.828 [info]: Request-ID is : 0df237a6cb904977b4b8219fa31f9d64
2023-06-10 01:36:21.828 [debug]: Request URL https://api.trustedservices.intel.com/sgx/certification/v4/pckcerts
2023-06-10 01:36:21.828 [error]: Intel PCS server returns error(404).
2023-06-10 01:36:21.828 [error]: Intel PCS server returns error. Error code : 404
2023-06-10 01:36:21.828 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:126:12)
    at async Module.getPckCert (file:///opt/intel/sgx-dcap-pccs/services/pckcertService.js:115:16)
    at async getPckCert (file:///opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:77:25)
2023-06-10 01:36:21.829 [info]: 127.0.0.1 - - [10/Jun/2023:01:36:21 +0000] "GET /sgx/certification/v4/pckcert?qeid=B73B400AC95413ED3F1B2652BE58DC8D&encrypted_ppid=D19D8B6776EFFEC0BA3D507A4DCFC9D0095DF5CF2DCBC2F8CC77AED1C53FB6E6A479E9E8BE16B0CA610423EEF5F9F0A8780B9796DCEB2AE97D76EDD65365A0F556720B1E535B3F63630D72012D71D818AA8158992AA527F72015AAA55981B9794B7041430DC41EBD1E6525B4CE3A8F203415DD1519E6B7B83C7F196E1613D407116890E9698416947381D2BF1792CB76B7C8D62751AF31481952C109978EABF5328ADF7E6ED446884CB1A97F93385509E38B547B58D897752DC3948087ABBD6A6D3C8CB286485658B1FFDCF030A26B3B02EAC0332D619D0FD9EE8E8CA6E8D380A2181D2508820B844164DAFB22A087B4893AB15935AB88B3EA0805C939AC47F86F4A1E0224A2DC4D02479F97E44BEA073D9FB28B3CC6DACFAF5A12F1162F15B009CEE567FD8DC4F9A2534EBA89BD4565C8B42202E4D109B1471B7AA63F676D581DF86C43C33B274AE7208F5DD15BF3E46E9D3093066C256551AE6861BAEFEBA8F0A0590B86234C7745ECEB69C0912BB56184655A850DAAAE033780ECCBF44C11&cpusvn=0505111303FF00FF0000000000000000&pcesvn=0E00&pceid=0000 HTTP/1.1" 404 32 "-" "-"
```

**Comment by PeizhongQiu** [comment]
When I run PCKIDRetrievalTool, the /opt/intel/sgx-dacp-pccs/logs/pccs_server.log adds:

```shell
2023-06-10 01:48:10.874 [info]: Client Request-ID : 1f676cdece8a4d46ade7d786831978e0
2023-06-10 01:48:12.028 [info]: Request-ID is : f88be6af4d65453dab8c4657f247b740
2023-06-10 01:48:12.028 [debug]: Request URL https://api.trustedservices.intel.com/sgx/certification/v4/pckcerts
2023-06-10 01:48:12.028 [error]: Intel PCS server returns error(400).
2023-06-10 01:48:12.028 [error]: Intel PCS server returns error. Error code : 400
2023-06-10 01:48:12.028 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:163:7)
    at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2023-06-10 01:48:12.029 [info]: 127.0.0.1 - - [10/Jun/2023:01:48:12 +0000] "POST /sgx/certification/v4/platforms HTTP/1.1" 404 32 "-" "-"
```

**Comment by jsun39** [comment]
1. it seems that the platform was not registered.
2. if the platform was registered, then the platform maybe was NOT production platform.

**Comment by PeizhongQiu** [comment]
What do you mean?

**Comment by jsun39** [comment]
you can refer to this doc: https://download.01.org/intel-sgx/sgx-dcap/1.16/linux/docs/Intel_SGX_DCAP_Multipackage_SW.pdf
in section 2.4.

I realized that I forget to ask one question: when you run PCKIDRetrieval tool, you run it in VM or in host?

**Comment by PeizhongQiu** [comment]
In host.

**Comment by PeizhongQiu** [comment]
I briefly read the chapter, but the chapter only stated that there are several Registration methods, and did not give a solution. How can I know whether the platform is registered?
I run the mpa_registration, and the /var/log/mpa_registration.log shows:
```shell
[10-06-2023 01:39:48] INFO: SGX Registration Agent version: 1.16.100.2
[10-06-2023 01:39:48] INFO: Starts Registration Agent Flow.
[10-06-2023 01:39:48] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[10-06-2023 01:39:48] INFO: Finished Registration Agent Flow.
``` 
And 
```shell
/opt/intel/sgx-ra-service$ sudo systemctl status mpa_registration_tool.service
○ mpa_registration_tool.service - Intel MPA Registration
     Loaded: loaded (/lib/systemd/system/mpa_registration_tool.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sat 2023-06-10 01:39:48 UTC; 14h ago
    Process: 197219 ExecStart=/opt/intel/sgx-ra-service/mpa_registration (code=exited, status=0/SUCCESS)
   Main PID: 197219 (code=exited, status=0/SUCCESS)
        CPU: 4ms

Jun 10 01:39:48 wark-i1 systemd[1]: Started Intel MPA Registration.
Jun 10 01:39:48 wark-i1 systemd[1]: mpa_registration_tool.service: Deactivated successfully.
``` 
Does it mean that my registration is successful?

**Comment by PeizhongQiu** [comment]
I solved this problem. It is the BIOS error. https://community.intel.com/t5/Intel-Software-Guard-Extensions/Can-not-get-platform-manifest-on-multi-package-platform/td-p/1395124
But when I run RemoteAttestation, the second round meets an error.
```shell
Secret successfully received from server.
Remote attestation success!
Call enclave_ra_close success.
Second round, we will try EPID algorithm.

Call sgx_get_extended_epid_group_id success.
MSG0 body generated -
4 bytes:
{
0x0, 0x0, 0x0, 0x0
}

Sending msg0 to remote attestation service provider.

Sent MSG0 to remote attestation service.

Call sgx_select_att_key_id success.
Call sgx_create_enclave success.
Call enclave_init_ra success.
Error, call sgx_ra_get_msg1_ex fail [main].
Call enclave_ra_close success.
```

**Comment by llly** [comment]
It's expected failure. Your platform doesn't support EPID attestation.

**Comment by PeizhongQiu** [comment]
At last, I wonder the meaning of some BIOS options: SGX Package Info In-Band Access, SGX LE Public Key Hash, and Software Guard Extensions Epoch. Can you help me?

**Comment by llly** [comment]
The details about `SGX Package Info In-Band Access` can be found in [`B.4. SGX Registration Package Info`](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_DCAP_Multipackage_SW.pdf)
`SGX LE Public Key Hash` is valid when `Launch Control Policy` set to Locked, to only allow a choose Launch Enclave. Usually, users don't need to set it.
Modifying the Owner Epoch will cause all persistent data protected by SGX to be lost.

**Comment by NookLook2014** [comment]
Same issue, and the BIOS sgx facory reset solved. Thanks!
